/*
Created: 02/16/2016
Model: api_customers_sybase
Database: Sybase ASE 15.7
*/


insert into eqbdataapi_tracks(id,country,type,name) values('id','country','type','name');
insert into eqbdataapi_tracks(id,country,type,name) values('AIK','USA','T','AIKEN');
insert into eqbdataapi_tracks(id,country,type,name) values('ALB','USA','T','ALBUQUERQUE');
insert into eqbdataapi_tracks(id,country,type,name) values('ANF','USA','T','ANTHONY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('AP ','USA','T','ARLINGTON');
insert into eqbdataapi_tracks(id,country,type,name) values('AQA','USA','T','AMERICAN QUARTER HORSE ASSOCIATION');
insert into eqbdataapi_tracks(id,country,type,name) values('AQU','USA','T','AQUEDUCT');
insert into eqbdataapi_tracks(id,country,type,name) values('ARP','USA','T','ARAPAHOE PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('ATH','USA','T','ATLANTA');
insert into eqbdataapi_tracks(id,country,type,name) values('ATL','USA','T','ATLANTIC CITY');
insert into eqbdataapi_tracks(id,country,type,name) values('ATO','USA','T','HORSEMEN''S ATOKAD DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('BC ','USA','T','BREEDERS CUP');
insert into eqbdataapi_tracks(id,country,type,name) values('BCF','USA','T','BROWN COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('BEL','USA','T','BELMONT PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('BEU','USA','T','BEULAH PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('BHP','USA','T','BETFAIR HOLLYWOOD PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('BIR','USA','T','BIRMINGHAM TURF CLUB');
insert into eqbdataapi_tracks(id,country,type,name) values('BKF','USA','T','BLACK FOOT');
insert into eqbdataapi_tracks(id,country,type,name) values('BM ','USA','T','BAY MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('BMF','USA','T','BAY MEADOWS FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('BOI','USA','T','LES BOIS PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('BOW','USA','T','BOWIE');
insert into eqbdataapi_tracks(id,country,type,name) values('BRD','USA','T','BLUE RIBBON DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('BRN','USA','T','HARNEY COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('BRO','USA','T','BROOKHILL FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('BSR','USA','T','BARRETTS RACE MEET AT FAIRPLEX');
insert into eqbdataapi_tracks(id,country,type,name) values('BTP','USA','T','BELTERRA PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('CAM','USA','T','CAMDEN');
insert into eqbdataapi_tracks(id,country,type,name) values('CAS','USA','T','CASSIA COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('CBY','USA','T','CANTERBURY PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('CD ','USA','T','CHURCHILL DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('CHA','USA','T','CHARLESTON');
insert into eqbdataapi_tracks(id,country,type,name) values('CHL','USA','T','CHARLOTTE');
insert into eqbdataapi_tracks(id,country,type,name) values('CLM','USA','T','CLEMMONS');
insert into eqbdataapi_tracks(id,country,type,name) values('CLS','USA','T','COLUMBUS');
insert into eqbdataapi_tracks(id,country,type,name) values('CNL','USA','T','COLONIAL DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('CPW','USA','T','CHIPPEWA DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('CRC','USA','T','CALDER RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('CT ','USA','T','HOLLYWOOD CASINO AT CHARLES TOWN RACES');
insert into eqbdataapi_tracks(id,country,type,name) values('CWF','USA','T','CENTRAL WYOMING FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('DAY','USA','T','DAYTON');
insert into eqbdataapi_tracks(id,country,type,name) values('DED','USA','T','DELTA DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('DEL','USA','T','DELAWARE PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('DET','USA','T','DETROIT RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('DG ','USA','T','COCHISE COUNTY FAIR @ DOUGLAS');
insert into eqbdataapi_tracks(id,country,type,name) values('DMR','USA','T','DEL MAR');
insert into eqbdataapi_tracks(id,country,type,name) values('DUB','USA','T','DUBAI RACING');
insert into eqbdataapi_tracks(id,country,type,name) values('DUN','USA','T','GREENELEE COUNTY FAIR @ DUNCAN');
insert into eqbdataapi_tracks(id,country,type,name) values('DUQ','USA','T','DU QUOIN');
insert into eqbdataapi_tracks(id,country,type,name) values('DXD','USA','T','DIXIE DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('ED ','USA','T','ENERGY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('ELK','USA','T','ELKO COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('ELP','USA','T','ELLIS PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('ELY','USA','T','WHITE PINE RACING');
insert into eqbdataapi_tracks(id,country,type,name) values('EMD','USA','T','EMERALD DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('EMT','USA','T','EMMETT');
insert into eqbdataapi_tracks(id,country,type,name) values('EUR','USA','T','EUREKA');
insert into eqbdataapi_tracks(id,country,type,name) values('EVD','USA','T','EVANGELINE DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('FAI','USA','T','FAIR HILL');
insert into eqbdataapi_tracks(id,country,type,name) values('FAR','USA','T','NORTH DAKOTA HORSE PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('FAX','USA','T','FAIRFAX');
insert into eqbdataapi_tracks(id,country,type,name) values('FER','USA','T','FERNDALE');
insert into eqbdataapi_tracks(id,country,type,name) values('FG ','USA','T','FAIR GROUNDS');
insert into eqbdataapi_tracks(id,country,type,name) values('FH ','USA','T','FAR HILLS');
insert into eqbdataapi_tracks(id,country,type,name) values('FL ','USA','T','FINGER LAKES');
insert into eqbdataapi_tracks(id,country,type,name) values('FMT','USA','T','FAIR MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('FNO','USA','T','FRESNO');
insert into eqbdataapi_tracks(id,country,type,name) values('FON','USA','T','FONNER PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('FP ','USA','T','FAIRMOUNT PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('FPL','USA','T','FAIR PLAY PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('FPX','USA','T','FAIRPLEX PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('FTP','USA','T','FORT PIERRE');
insert into eqbdataapi_tracks(id,country,type,name) values('FX ','USA','T','FOXFIELD');
insert into eqbdataapi_tracks(id,country,type,name) values('GBF','USA','T','GREAT BARRINGTON FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('GF ','USA','T','GREAT FALLS');
insert into eqbdataapi_tracks(id,country,type,name) values('GG ','USA','T','GOLDEN GATE FIELDS');
insert into eqbdataapi_tracks(id,country,type,name) values('GIL','USA','T','GILLESPIE COUNTY FAIRGROUND');
insert into eqbdataapi_tracks(id,country,type,name) values('GLD','USA','T','GREAT LAKES DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('GLN','USA','T','GLYNDON');
insert into eqbdataapi_tracks(id,country,type,name) values('GN ','USA','T','GRAND NATIONAL');
insert into eqbdataapi_tracks(id,country,type,name) values('GP ','USA','T','GULFSTREAM PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('GPW','USA','T','GULFSTREAM PARK WEST');
insert into eqbdataapi_tracks(id,country,type,name) values('GRA','USA','T','GREEN ACRES');
insert into eqbdataapi_tracks(id,country,type,name) values('GRM','USA','T','GREAT MEADOW');
insert into eqbdataapi_tracks(id,country,type,name) values('GRP','USA','T','GRANTS PASS');
insert into eqbdataapi_tracks(id,country,type,name) values('GV ','USA','T','GENESEE VALLEY');
insert into eqbdataapi_tracks(id,country,type,name) values('HAW','USA','T','HAWTHORNE');
insert into eqbdataapi_tracks(id,country,type,name) values('HCF','USA','T','HUMBOLDT COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('HIA','USA','T','HIALEAH PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HOL','USA','T','HOLLYWOOD PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HOO','USA','T','HOOSIER PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HOU','USA','T','SAM HOUSTON RACE PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HP ','USA','T','HAZEL PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HPO','USA','T','HORSEMEN''S PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('INC','USA','T','INCOMPASS');
insert into eqbdataapi_tracks(id,country,type,name) values('IND','USA','T','INDIANA GRAND RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('ING','USA','T','INGLESIDE');
insert into eqbdataapi_tracks(id,country,type,name) values('INT','USA','T','International Simulcast');
insert into eqbdataapi_tracks(id,country,type,name) values('JRM','USA','T','JEROME COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('KD ','USA','T','KENTUCKY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('KEE','USA','T','KEENELAND');
insert into eqbdataapi_tracks(id,country,type,name) values('KSP','USA','T','KALISPELL');
insert into eqbdataapi_tracks(id,country,type,name) values('LA ','USA','T','LOS ALAMITOS');
insert into eqbdataapi_tracks(id,country,type,name) values('LAD','USA','T','LOUISIANA DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('LAM','USA','T','LA MESA PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('LBT','USA','T','LAUREL BROWN RACETRACK');
insert into eqbdataapi_tracks(id,country,type,name) values('LEV','USA','T','LITTLE EVERGLADES');
insert into eqbdataapi_tracks(id,country,type,name) values('LEX','USA','T','LEXINGTON');
insert into eqbdataapi_tracks(id,country,type,name) values('LNN','USA','T','LINCOLN RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('LRC','USA','T','LOS ALAMITOS RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('LRL','USA','T','LAUREL PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('LS ','USA','T','LONE STAR PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('MAF','USA','T','MARIAS FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('MAL','USA','T','MALVERN');
insert into eqbdataapi_tracks(id,country,type,name) values('MAN','USA','T','MANOR DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('MAR','USA','T','MARLBORO');
insert into eqbdataapi_tracks(id,country,type,name) values('MC ','USA','T','MILES CITY');
insert into eqbdataapi_tracks(id,country,type,name) values('MED','USA','T','MEADOWLANDS');
insert into eqbdataapi_tracks(id,country,type,name) values('MID','USA','T','MIDDLEBURG');
insert into eqbdataapi_tracks(id,country,type,name) values('MNR','USA','T','MOUNTAINEER CASINO RACETRACK '|| '&' ||' RESORT');
insert into eqbdataapi_tracks(id,country,type,name) values('MON','USA','T','MONKTON');
insert into eqbdataapi_tracks(id,country,type,name) values('MOR','USA','T','MORVEN PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('MPM','USA','T','MT. PLEASANT MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('MTH','USA','T','MONMOUTH PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('MTP','USA','T','MONTPELIER');
insert into eqbdataapi_tracks(id,country,type,name) values('MVR','USA','T','MAHONING VALLEY RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('NVD','USA','T','NORTHVILLE DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('OKR','USA','T','OAK RIDGE');
insert into eqbdataapi_tracks(id,country,type,name) values('ONE','USA','T','ONEIDA COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('OP ','USA','T','OAKLAWN PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('OSA','USA','T','OAK TREE AT SANTA ANITA');
insert into eqbdataapi_tracks(id,country,type,name) values('OTC','USA','T','OCALA TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OTH','USA','T','OAK TREE AT HOLLYWOOD PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('OTP','USA','T','OAK TREE AT PLEASANTON');
insert into eqbdataapi_tracks(id,country,type,name) values('PEN','USA','T','PENN NATIONAL');
insert into eqbdataapi_tracks(id,country,type,name) values('PHA','USA','T','PHILADELPHA PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('PID','USA','T','PRESQUE ISLE DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('PIM','USA','T','PIMLICO');
insert into eqbdataapi_tracks(id,country,type,name) values('PLN','USA','T','PLEASANTON');
insert into eqbdataapi_tracks(id,country,type,name) values('PM ','USA','T','PORTLAND MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('PMB','USA','T','PALM BEACH POLO CLUB');
insert into eqbdataapi_tracks(id,country,type,name) values('PMT','USA','T','PINE MTN-CALLAWAY GARDEN');
insert into eqbdataapi_tracks(id,country,type,name) values('PNL','USA','T','PINNACLE RACE COURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('POD','USA','T','POCATELLO DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('PRM','USA','T','PRAIRIE MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('PRV','USA','T','CROOKED RIVER ROUNDUP');
insert into eqbdataapi_tracks(id,country,type,name) values('PRX','USA','T','PARX RACING');
insert into eqbdataapi_tracks(id,country,type,name) values('PW ','USA','T','PERCY WARNER');
insert into eqbdataapi_tracks(id,country,type,name) values('RB ','USA','T','RED BANK');
insert into eqbdataapi_tracks(id,country,type,name) values('RD ','USA','T','RIVER DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('RDM','USA','T','RED MILE');
insert into eqbdataapi_tracks(id,country,type,name) values('RET','USA','T','RETAMA PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('RIL','USA','T','RILLITO');
insert into eqbdataapi_tracks(id,country,type,name) values('RKM','USA','T','ROCKINGHAM PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('RP ','USA','T','REMINGTON PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('RUI','USA','T','RUIDOSO DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('RUP','USA','T','RUPERT DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SA ','USA','T','SANTA ANITA PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('SAC','USA','T','SACRAMENTO');
insert into eqbdataapi_tracks(id,country,type,name) values('SAF','USA','T','GRAHAM COUNTY FAIR @ SAFFORD');
insert into eqbdataapi_tracks(id,country,type,name) values('SAR','USA','T','SARATOGA');
insert into eqbdataapi_tracks(id,country,type,name) values('SDY','USA','T','SANDY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SEO','USA','T','SEARCH ENGINE OPTIMIZATION');
insert into eqbdataapi_tracks(id,country,type,name) values('SFE','USA','T','SANTA FE');
insert into eqbdataapi_tracks(id,country,type,name) values('SH ','USA','T','STRAWBERRY HILL');
insert into eqbdataapi_tracks(id,country,type,name) values('SHD','USA','T','SHENNANDOAH DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SHW','USA','T','SHAWAN DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SJD','USA','T','SAN JUAN DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SLR','USA','T','SAN LUIS REY TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SOL','USA','T','SOLANO');
insert into eqbdataapi_tracks(id,country,type,name) values('SON','USA','T','SANTA CRUZ COUNTY FAIR @ SONOITA');
insert into eqbdataapi_tracks(id,country,type,name) values('SOP','USA','T','SOUTHERN PINES');
insert into eqbdataapi_tracks(id,country,type,name) values('SPT','USA','T','SPORTSMAN''S PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('SR ','USA','T','SANTA ROSA');
insert into eqbdataapi_tracks(id,country,type,name) values('SRP','USA','T','SUNRAY PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('STK','USA','T','STOCKTON');
insert into eqbdataapi_tracks(id,country,type,name) values('STN','USA','T','STONEYBROOK AT FIVE POINTS');
insert into eqbdataapi_tracks(id,country,type,name) values('SUD','USA','T','SUN DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SUF','USA','T','SUFFOLK DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SUN','USA','T','SUNLAND PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('SWF','USA','T','SWEETWATER DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('TAM','USA','T','TAMPA BAY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('TDN','USA','T','THISTLEDOWN');
insert into eqbdataapi_tracks(id,country,type,name) values('TGD','USA','T','TIOGA DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('TIL','USA','T','TILLAMOOK COUNTY FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('TIM','USA','T','TIMONIUM');
insert into eqbdataapi_tracks(id,country,type,name) values('TP ','USA','T','TURFWAY PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('TRB','USA','T','Thoroughbred Racing Protective Bureau');
insert into eqbdataapi_tracks(id,country,type,name) values('TRU','USA','T','Truform test');
insert into eqbdataapi_tracks(id,country,type,name) values('TRY','USA','T','TRYON');
insert into eqbdataapi_tracks(id,country,type,name) values('TUP','USA','T','TURF PARADISE');
insert into eqbdataapi_tracks(id,country,type,name) values('UN ','USA','T','EASTERN OREGON LIVESTOCK SHOW');
insert into eqbdataapi_tracks(id,country,type,name) values('UNI','USA','T','PENNSYLVANIA HUNT CUP');
insert into eqbdataapi_tracks(id,country,type,name) values('VS ','USA','T','VIRTUAL STABLE');
insert into eqbdataapi_tracks(id,country,type,name) values('WDS','USA','T','THE WOODLANDS');
insert into eqbdataapi_tracks(id,country,type,name) values('WIL','USA','T','WILLOWDALE STEEPLECHASE');
insert into eqbdataapi_tracks(id,country,type,name) values('WMF','USA','T','WESTERN MT FAIR');
insert into eqbdataapi_tracks(id,country,type,name) values('WNT','USA','T','WINTERTHUR');
insert into eqbdataapi_tracks(id,country,type,name) values('WPR','USA','T','WHITE PINE RACEWAY');
insert into eqbdataapi_tracks(id,country,type,name) values('WRD','USA','T','WILL ROGERS DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('WTS','USA','T','WAITSBURG RACE TRACK');
insert into eqbdataapi_tracks(id,country,type,name) values('WW ','USA','T','WALLA WALLA');
insert into eqbdataapi_tracks(id,country,type,name) values('WYO','USA','T','WYOMING DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('YAV','USA','T','YAVAPAI DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('YD ','USA','T','YELLOWSTONE DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('YM ','USA','T','YAKIMA MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('ZIA','USA','T','ZIA PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('CMR','PR ','T','CAMARERO RACE TRACK');
insert into eqbdataapi_tracks(id,country,type,name) values('PR ','PR ','T','PUERTO RICO');
insert into eqbdataapi_tracks(id,country,type,name) values('ABT','CAN','T','ALBERTA DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('AJX','CAN','T','AJAX DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('ASD','CAN','T','ASSINIBOIA DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('DEP','CAN','T','DESERT PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('FE ','CAN','T','FORT ERIE');
insert into eqbdataapi_tracks(id,country,type,name) values('GPR','CAN','T','GRANDE PRAIRIE');
insert into eqbdataapi_tracks(id,country,type,name) values('HST','CAN','T','HASTINGS RACECOURSE');
insert into eqbdataapi_tracks(id,country,type,name) values('KAM','CAN','T','KAMLOOPS');
insert into eqbdataapi_tracks(id,country,type,name) values('KIN','CAN','T','KIN PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('LBG','CAN','T','LETHBRIDGE');
insert into eqbdataapi_tracks(id,country,type,name) values('MD ','CAN','T','MARQUIS DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('MDA','CAN','T','MELVILLE DISTRICT AGRIPAR');
insert into eqbdataapi_tracks(id,country,type,name) values('MIL','CAN','T','MILLARVILLE');
insert into eqbdataapi_tracks(id,country,type,name) values('NP ','CAN','T','NORTHLANDS PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('PIC','CAN','T','PICOV DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('RPD','CAN','T','ROSSBURN PARKLAND DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SAN','CAN','T','SANDOWN PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('SND','CAN','T','SUNFLOWER');
insert into eqbdataapi_tracks(id,country,type,name) values('STP','CAN','T','STAMPEDE PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('WO ','CAN','T','WOODBINE');
insert into eqbdataapi_tracks(id,country,type,name) values('ABC','USA','C','ABRACADABRA FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('ADR','USA','C','ADRIAN SOTO RACING STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('ADS','USA','C','ADENA SPRINGS FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('AEF','USA','C','ANOTHER EPISODE FARM INC.');
insert into eqbdataapi_tracks(id,country,type,name) values('AFT','USA','C','ANDOR FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('AHT','USA','C','ATLANTA HALL TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('AKI','USA','C','AKINDALE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('ARI','USA','C','ARINDEL FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('ASF','USA','C','ALL SEVEN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('ASH','USA','C','ASHWELL STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('BDW','USA','C','BRIDLEWOOD FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('BES','USA','C','BESILU STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('BLF','USA','C','BOLO FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('BLK','USA','C','BLACKWOOD STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('BLT','USA','C','BRADFORD LANE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('BLV','USA','C','BELVOIR TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('BNT','USA','C','BENTON TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('BON','USA','C','BONITA FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('BRM','USA','C','BREAKING MAIDENS FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('BRS','USA','C','BURNS RACING STABLE');
insert into eqbdataapi_tracks(id,country,type,name) values('BTB','USA','C','BIGHEART THOROUGHBREDS');
insert into eqbdataapi_tracks(id,country,type,name) values('BTC','USA','C','BRAEBURN');
insert into eqbdataapi_tracks(id,country,type,name) values('BTF','USA','C','BOB TROUT FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('BWC','USA','C','Bluewater Creek Farm');
insert into eqbdataapi_tracks(id,country,type,name) values('CBQ','USA','C','CHABBOQUESSET TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CBS','USA','C','Cool Breeze Stables');
insert into eqbdataapi_tracks(id,country,type,name) values('CBT','USA','C','CANYON BREEZE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CBV','USA','C','CABIN VIEW FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('CCT','USA','C','THE TRAINING CENTER AT COPPER CROWNE');
insert into eqbdataapi_tracks(id,country,type,name) values('CDH','USA','C','CARDINAL HILL');
insert into eqbdataapi_tracks(id,country,type,name) values('CDT','USA','C','CHURCHILL TRAINING');
insert into eqbdataapi_tracks(id,country,type,name) values('CFR','USA','C','CENTRAL FLORIDA RANCHES');
insert into eqbdataapi_tracks(id,country,type,name) values('CGR','USA','C','CIRCLE G RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('CHM','USA','C','CHAMPAGNE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('CIM','USA','C','CIMARRON FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('CM ','USA','C','CLASSIC MILE');
insert into eqbdataapi_tracks(id,country,type,name) values('CMB','USA','C','CUMBERLAND COUNTY FAIRGROUNDS');
insert into eqbdataapi_tracks(id,country,type,name) values('CMF','USA','C','CALUMET FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CNR','USA','C','CANYON ROAD TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CNS','USA','C','COLTS NECK STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('CRU','USA','C','CRUPI''S NEW CASTLE FARM INC.');
insert into eqbdataapi_tracks(id,country,type,name) values('CSB','USA','C','CASTLEBROOK TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CTS','USA','C','CLOUSTON TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CTT','USA','C','CAIN''S THOROUGHBRED TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('CWS','USA','C','CROWN''S WAY SOUTH');
insert into eqbdataapi_tracks(id,country,type,name) values('DBR','USA','C','DOUBLE D RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('DD ','USA','C','DIAMOND D RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('DDF','USA','C','DOUBLE DIAMOND FARM AND TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('DDR','USA','C','DIAMOND D RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('DDT','USA','C','DERBY DAYS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('DER','USA','C','DERBY DREAMS TRAINING '|| '&' ||' EQUINE CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('DFF','USA','C','DEER FIELD FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('DLF','USA','C','DRAGONS LYRE FARMS');
insert into eqbdataapi_tracks(id,country,type,name) values('DMC','USA','C','DMC TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('DON','USA','C','DONIDA TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('DTD','USA','C','DARE TO DREAM FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('DTR','USA','C','DELTA TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('DWM','USA','C','DREAM WITH ME STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('ECL','USA','C','ECLIPSE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('ECR','USA','C','ELK CREEK RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('ECT','USA','C','EAST CAROLINA TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EDT','USA','C','EMPRESS DOWNS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EGL','USA','C','EAGLE ROCK DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('EIS','USA','C','EISAMAN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('ELL','USA','C','ELLOREE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EME','USA','C','EMERALD PASTURES TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EPF','USA','C','EAGLE POINT FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('EPR','USA','C','EL PRIMERO TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EQL','USA','C','EQUELS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('ETC','USA','C','ECLIPSE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EVR','USA','C','EVERGREEN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EVT','USA','C','EVANGELINE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('EWT','USA','C','EDDIE WOODS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('FBF','USA','C','FOX BROWN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('FCL','USA','C','FAIRCLOTH TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('FFM','USA','C','FOLK FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('FID','USA','C','FIDELIA STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('FOL','USA','C','FOLSOM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('FPF','USA','C','FORT PLAINS FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('FRF','USA','C','FRANKS FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('FRN','USA','C','FRONTERA TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('FRO','USA','C','FROST TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('FXP','USA','C','FOX POINT FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('GD ','USA','C','GALWAY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('GDC','USA','C','GOOD CHANCE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('GDF','USA','C','GARYDALE FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('GFT','USA','C','GOODWIN FARMS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('GLC','USA','C','GLOCKENBURG LLC');
insert into eqbdataapi_tracks(id,country,type,name) values('GLF','USA','C','GREAT LAKES FAIR TRAINING FACILITY');
insert into eqbdataapi_tracks(id,country,type,name) values('GLM','USA','C','GOLDMARK');
insert into eqbdataapi_tracks(id,country,type,name) values('GLP','USA','C','THE GALLOPS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('GLS','USA','C','GOLDEN LEGACY STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('GNN','USA','C','GUNN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('GOE','USA','C','GRAND OAKS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('GPF','USA','C','GENUINE PLEASURE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('GRS','USA','C','GARRISON FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('GTC','USA','C','GREENTREE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('GTW','USA','C','GATEWAY DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('GVT','USA','C','GREEN VALLEY TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HBH','USA','C','HUNTER BROOK HORSE FARM INC.');
insert into eqbdataapi_tracks(id,country,type,name) values('HDR','USA','C','HARTLEY DERENZO TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HDT','USA','C','H '|| '&' ||' D TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HER','USA','C','HERITAGE FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HHC','USA','C','HURRICANE HALL TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HMP','USA','C','HORSEMAN''S PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HPT','USA','C','HIGHPOINT FARM AND TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HRF','USA','C','HAWKINRIDGE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('HTC','USA','C','HARMONY TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HTF','USA','C','HICKORY TREE FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HTG','USA','C','HERITAGE PARK');
insert into eqbdataapi_tracks(id,country,type,name) values('HUF','USA','C','HUNTER FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('HYT','USA','C','HYATT FARM AND TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('IAF','USA','C','IRISH ACRES FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('ISA','USA','C','ISABELLA CO-EXPO TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('ITC','USA','C','INFIELDS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('JDF','USA','C','JOE DAN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('JDM','USA','C','JDM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('JHF','USA','C','JORDAN''S HORSE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('JMF','USA','C','JUDDMONTE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('JOU','USA','C','JOURNEYS END TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('JUB','USA','C','JUBILEE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('JVR','USA','C','J V RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('KNF','USA','C','KINSMAN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('LCT','USA','C','LEVY COUNTY TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('LGF','USA','C','LEGACY FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('LIT','USA','C','LITTLE BROOK TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('LMB','USA','C','LAMBHOLM SOUTH TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('LOF','USA','C','LONE OAK FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('LVT','USA','C','LAKE VIEW TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MBF','USA','C','MCKATHAN BROTHERS FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('MCU','USA','C','MCCUTCHEN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MER','USA','C','MERCURY EQUINE CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MFT','USA','C','MCKATHAN FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MIH','USA','C','MIAMI HORSEMEN''S ASSOCIATION TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MKT','USA','C','MACKABEN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MKY','USA','C','MASARKYTOWN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MME','USA','C','MARLYN MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('MOG','USA','C','MOMENT OF GLORY TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MRT','USA','C','MARTINSVILLE FAIRGROUNDS');
insert into eqbdataapi_tracks(id,country,type,name) values('MRX','USA','C','MARGAUX FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('MRY','USA','C','MERRYLAND FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('MST','USA','C','MID SOUTH TRAINING');
insert into eqbdataapi_tracks(id,country,type,name) values('MTC','USA','C','MIDDLETOWN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('MWF','USA','C','MAYO WEST FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('NAD','USA','C','NAD AL SHEBA');
insert into eqbdataapi_tracks(id,country,type,name) values('NBS','USA','C','NIALL BRENNAN STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('NET','USA','C','NEW EPISODE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('NHF','USA','C','NEW HAVEN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('NJF','USA','C','NELSON JONES FARMS AND TRAINING CENTER INC.');
insert into eqbdataapi_tracks(id,country,type,name) values('NPR','USA','C','NAPIER''S TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('NTC','USA','C','NOBLES TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('NWF','USA','C','NEW FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OEC','USA','C','OAKRIDGE EQUINE CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OHC','USA','C','OCALA HORSE FARM COMPLEX');
insert into eqbdataapi_tracks(id,country,type,name) values('OJO','USA','C','OCALA JOCKEY CLUB TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OKL','USA','C','OAKLEAF TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OLY','USA','C','OLYMPIC HILL TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('ORT','USA','C','ORTING TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OTF','USA','C','OCALA THOROUGHBRED FARMS');
insert into eqbdataapi_tracks(id,country,type,name) values('OVR','USA','C','OVERBROOK TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('OWT','USA','C','OCALA RANCHES');
insert into eqbdataapi_tracks(id,country,type,name) values('OXF','USA','C','OXFORD TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('PAY','USA','C','PAYSON PARK TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('PBD','USA','C','PALM BEACH DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('PCF','USA','C','PINK CROWN FARMS');
insert into eqbdataapi_tracks(id,country,type,name) values('PDA','USA','C','PADUA TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('PEG','USA','C','PEGASUS THOROUGHBRED TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('PER','USA','C','PERFENICK FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('PJT','USA','C','PAUL JONES TRAINING CENTER TULAROSA');
insert into eqbdataapi_tracks(id,country,type,name) values('PMM','USA','C','PALM MEADOWS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('PNS','USA','C','PENINSULA FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('PPX','USA','C','PLEASANT PASTURE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('PTT','USA','C','PALMETTO THOROUGHBRED TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('PVF','USA','C','POND VIEW FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('PYN','USA','C','PAYTON TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('QWF','USA','C','QUIET WOMAN FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('QWS','USA','C','QUIET WOMAN FARM SOUTH');
insert into eqbdataapi_tracks(id,country,type,name) values('RBT','USA','C','RED BOB TRAINING FACILITY');
insert into eqbdataapi_tracks(id,country,type,name) values('RCE','USA','C','RACING EDGE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('RDE','USA','C','RED EARTH TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('REB','USA','C','REBER RANCH TRAINING TRACK');
insert into eqbdataapi_tracks(id,country,type,name) values('RIG','USA','C','RIGBIE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('RIS','USA','C','RISING SUN FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('RKV','USA','C','ROCKY VALLEY');
insert into eqbdataapi_tracks(id,country,type,name) values('RMF','USA','C','R '|| '&' ||' M FARMS');
insert into eqbdataapi_tracks(id,country,type,name) values('RMT','USA','C','ROSS MEADOWS');
insert into eqbdataapi_tracks(id,country,type,name) values('ROF','USA','C','RED OAK FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('RQH','USA','C','RQHS Mile');
insert into eqbdataapi_tracks(id,country,type,name) values('RSD','USA','C','RIVERSIDE DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('SAB','USA','C','SABINE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SAM','USA','C','SAM-SON FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SBA','USA','C','STONEBRIDGE ANNEX');
insert into eqbdataapi_tracks(id,country,type,name) values('SBF','USA','C','SHADYBROOK FARM INC.');
insert into eqbdataapi_tracks(id,country,type,name) values('SBG','USA','C','STONEBRIDGE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SCH','USA','C','SCHULTZ RACING STABLE');
insert into eqbdataapi_tracks(id,country,type,name) values('SCN','USA','C','SCANLON TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SCT','USA','C','SANDERS CREEK TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SER','USA','C','SERENDIPITY FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SFC','USA','C','SOUTH FLORIDA TROTTING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SFT','USA','C','SUNNYSIDE FARM TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SGC','USA','C','STARTING GATE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SGF','USA','C','SAGAMORE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SHF','USA','C','SILVERTON HILL FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SKF','USA','C','STRICKLAND FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SKL','USA','C','SKY''S THE LIMIT');
insert into eqbdataapi_tracks(id,country,type,name) values('SKY','USA','C','SKYLIGHT TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SLF','USA','C','SOLERA FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SOT','USA','C','SILVER OAKS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SPC','USA','C','STARTING POINT TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SSS','USA','C','STANLEY STABLES');
insert into eqbdataapi_tracks(id,country,type,name) values('SST','USA','C','SUNRISE STABLE SOUTH');
insert into eqbdataapi_tracks(id,country,type,name) values('SSX','USA','C','SAGE AND SAND TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('STB','USA','C','STONEBRIDGE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('STC','USA','C','SALLISAW EQUINE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('STF','USA','C','STARSFELL FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('STO','USA','C','STONY OAK TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('STR','USA','C','SINATRA THOROUGHBRED RACING');
insert into eqbdataapi_tracks(id,country,type,name) values('STS','USA','C','SIESTA SUN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('STT','USA','C','STONESTREET TRAINING LLC');
insert into eqbdataapi_tracks(id,country,type,name) values('STU','USA','C','STUTTS STABLE');
insert into eqbdataapi_tracks(id,country,type,name) values('STW','USA','C','STONEWALL FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SUT','USA','C','SUTHERLAND FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('SWH','USA','C','SWEETWATER HORSE TRACK AND TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SWT','USA','C','SANDY WOODS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SYC','USA','C','SYCAMORE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('SYL','USA','C','SYLMAR FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('TAP','USA','C','TAPETA FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('TAT','USA','C','T '|| '&' ||' A TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('TBR','USA','C','TB RACING');
insert into eqbdataapi_tracks(id,country,type,name) values('TCC','USA','C','THOROUGHBRED CHAMPIONS TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('THL','USA','C','THORNHILL FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('THT','USA','C','TARHEEL TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('TOO','USA','C','TOOLE''S TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('TRE','USA','C','TREMONTON');
insert into eqbdataapi_tracks(id,country,type,name) values('TRT','USA','C','THUNDER RANCH TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('TSF','USA','C','eqbdataapi_tracksIDE FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('TST','USA','C','TRUE SOUTH TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('TTC','USA','C','THE THOROUGHBRED CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('TWR','USA','C','TEAM WORK RACING');
insert into eqbdataapi_tracks(id,country,type,name) values('VAN','USA','C','VANATTA TRACK AND TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('VHT','USA','C','VICTORY HAVEN TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('VIN','USA','C','VINERY STABLE');
insert into eqbdataapi_tracks(id,country,type,name) values('VQF','USA','C','VICTORY QUEST FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('WAC','USA','C','WASHINGTON COUNTY FAIRGROUNDS');
insert into eqbdataapi_tracks(id,country,type,name) values('WBR','USA','C','WEBER DOWNS');
insert into eqbdataapi_tracks(id,country,type,name) values('WCR','USA','C','WINDING CREEK FARMS');
insert into eqbdataapi_tracks(id,country,type,name) values('WCT','USA','C','WEBB CARROLL TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('WDB','USA','C','WOODBROOK FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('WFR','USA','C','WILD FALCON RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('WHL','USA','C','WHEELER TRAINING STATION');
insert into eqbdataapi_tracks(id,country,type,name) values('WKY','USA','C','WEST KY THOROUGHBRED TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('WLN','USA','C','WALNUT HALL');
insert into eqbdataapi_tracks(id,country,type,name) values('WM ','USA','C','WILLISTON MILE');
insert into eqbdataapi_tracks(id,country,type,name) values('WND','USA','C','WINDING OAKS FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('WOD','USA','C','WOODSIDE RANCH');
insert into eqbdataapi_tracks(id,country,type,name) values('WRC','USA','C','W R TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('WRT','USA','C','WINDY RIDGE TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('WSF','USA','C','WESFIELD FARM');
insert into eqbdataapi_tracks(id,country,type,name) values('WSR','USA','C','WINSTAR TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('WST','USA','C','WESTAMPTON FARMS');
insert into eqbdataapi_tracks(id,country,type,name) values('WTC','USA','C','WEBSTER TRAINING CENTER');
insert into eqbdataapi_tracks(id,country,type,name) values('WTT','USA','C','WILDCAT TRAINING CENTER');
